name: slice_job
description: A Flutter project for slice job.

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  material_color_gen: ^2.0.0
  provider: ^6.0.3
  sliding_clipped_nav_bar: ^3.1.0+2
  ionicons: ^0.1.2
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.1
  social_login_buttons: ^1.0.6+2
  pretty_json: ^2.0.0
  future_progress_dialog: ^0.2.0
  pinput: ^2.2.11
  file_picker: ^4.6.1
  intl: ^0.17.0
  path_provider: ^2.0.11

  connectivity_plus: ^2.3.5
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.4
  jiffy: ^5.0.0
  flutter_widget_from_html_core: ^0.8.5+3
  image_cropper: ^2.0.3
  webview_flutter_plus: ^0.3.0+2
  open_file: ^3.2.1
  share_plus: ^4.0.10
  google_maps_flutter: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/background.png"
  adaptive_icon_foreground: "assets/icon/foreground.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/panara_dialogs/
    - google_fonts/

  fonts:
    - family: AlegreyaSans
      fonts:
        - asset: google_fonts/AlegreyaSans-Thin.ttf
          weight: 100
        - asset: google_fonts/AlegreyaSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: google_fonts/AlegreyaSans-Light.ttf
          weight: 300
        - asset: google_fonts/AlegreyaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: google_fonts/AlegreyaSans-Regular.ttf
          weight: 400
        - asset: google_fonts/AlegreyaSans-Italic.ttf
          weight: 400
          style: italic
        - asset: google_fonts/AlegreyaSans-Medium.ttf
          weight: 500
        - asset: google_fonts/AlegreyaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: google_fonts/AlegreyaSans-Bold.ttf
          weight: 700
        - asset: google_fonts/AlegreyaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: google_fonts/AlegreyaSans-ExtraBold.ttf
          weight: 800
        - asset: google_fonts/AlegreyaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: google_fonts/AlegreyaSans-Black.ttf
          weight: 900
        - asset: google_fonts/AlegreyaSans-BlackItalic.ttf
          weight: 900
          style: italic